version: "3"
services:
  database:
    build: ./MySQL
    image: mymysqlimage
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
  wordpress:
    build: ./WordPress
    image: mywordpressimage
    depends_on:
      - database
    restart: always
    ports:
      - "80:80"
    volumes:
      - wpdata:/var/www/html"
volumes:
  dbdata: {}
  wpdata: {}
